
services:
  postgres:
    image: postgres:16-alpine
    container_name: alamar_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: alamar_monitoring
      POSTGRES_USER: alamar
      POSTGRES_PASSWORD: alamar123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
